### ISSUE TITLE
can't run

### ISSUE THREAD

**Issue by Littledragon-wxl** [F-Barto/LiDARTouch#1]

**Comment by Littledragon-wxl** [comment]
I have prepared the dataset now, but I won't be able to run the rest of it now, which is the "path configuration" step

**Comment by Littledragon-wxl** [comment]
D:\LiDARTouch-main\config\log_dir\default.yaml
I don't know how to set the path inside this file
If you could answer, I would greatly appreciate it

**Comment by F-Barto** [comment]
I've updated the README

See "Step 3: Paths configuration" in the README.

I forgot to add the `.env` file in the repo. I now provide a `.env_example`

the files in `\config\log_dir` are specific to HYDRA and should not be modified.

**Comment by Littledragon-wxl** [comment]
Thank for your reply. With your help, I have already solved the problem.It can run now.
